#!/bin/bash

sudo crontab -l > tmp
echo "0 0 * * * \
	sum1=\"\$(md5sum /etc/crontab | awk '{ print \$1 }')\" && \
	sum2=\"\$(cat /etc/crontab.log)\" && \
	if [ '\$sum1' != '\$sum2' ] ; then \
		md5sum /etc/crontab | awk '{ print \$1 }' > /etc/crontab.log && \
		echo '/etc/crontab was modified \$(date)' | mail -s '/etc/crontab modifier' root ; fi" >> tmp
sudo crontab tmp
rm tmp
